services:
  postgres:
    image: postgres:17
    container_name: road-to-immortal-db
    environment:
      POSTGRES_DB: road_to_immortal
      POSTGRES_USER: rti
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: